# Generated by Django 3.0.3 on 2020-02-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dateTime',
            new_name='created_at',
        ),
    ]
